# Site settings

title: Ryuu's archives
SEOTitle: 安静记录生活 | Ryuu's archives
header-img: img/post-bg-desk.jpg
email: ryuuseiku.home@gmail.com
description: "Every failure is leading towards success."
keyword: "Ryuu's archives"
url: "http://anqiaoqiao.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/anqiaoqiao/anqiaoqiaoblog.github.io" # you code repository

# Sidebar settings

sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "「宁静致远。」"
sidebar-avatar: /img/about-me.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings

RSS: false
zhihu_username:     asher-54-91
github_username:    anqiaoqiao
jianshu_username:   cbf89eb99a0e
twitter_username:   sikewalo

# Build settings

permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true

# Gems
# from PR#40, to support local preview for Jekyll 3.0

gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown

markdown: kramdown
highlighter: rouge
kramdown:
input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: seikyoriu

# Gitalk

gitalk:
  enable: false
  clientID: 05286a005b6e072906dc
  clientSecret: 3220c568c538288a8f54628e95d7d253a2ca471c
  repo: anqiaoqiaoblog.github.io
  owner: anqiaoqiaoblog.github.io
  admin: anqiaoqiaoblog.github.io
  id: bolgcommit
  distractionFreeMode: true

# Analytics settings
# Google Analytics

ga_track_id: 'UA-131432876-1'            # Format: UA-xxxxxx-xx
ga_domain: ryuus-archives.com             # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Featured Tags

featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps

chrome-tab-theme-color: "#000000"
service-worker: true

# Links

friends: [
    {
        title: "wechat",
        href: "https://picgo.oss-ap-northeast-1.aliyuncs.com/wx_qrcode.jpg?x-oss-process=style/mystyle"
    },{
        title: "line",
        href: "https://picgo.oss-ap-northeast-1.aliyuncs.com/img/line_qrcode.jpg?x-oss-process=style/mystyle"
    }
]

theme: jekyll-theme-hacker
